#### Testing api endpoints

#### Test GEt

GET http://localhost:3001/api/blogs


#### Test Post

POST  http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MjE3MzhjYmNmY2NiODE3NzQ0MzNmZiIsImlhdCI6MTczMDQxNTM1NSwiZXhwIjoxNzMwNDE4OTU1fQ.ObjF5ByDAiK0YbtLyBZ7WFLe2yV69XNFPX1XiQ-YThQ


{
    "title":"juanito ",
    "author":"juanito",
    "url": "german.com",
    "likes": 1
}


### Test Delete Blog

DELETE http://localhost:3001/api/blogs/67240c8da5559f9a1ff65ff8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3MjE3MzhjYmNmY2NiODE3NzQ0MzNmZiIsImlhdCI6MTczMDQxNTM1NSwiZXhwIjoxNzMwNDE4OTU1fQ.ObjF5ByDAiK0YbtLyBZ7WFLe2yV69XNFPX1XiQ-YThQ


#### Test User Post

POST  http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

#### Test Get User
GET http://localhost:3001/api/users



#### Test User Login

POST  http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}