#### Testing api endpoints

#### Test GEt

GET http://localhost:3001/api/blogs


#### Test Post

POST  http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: 


{
    "title":"juanito ",
    "author":"juanito",
    "url": "german.com",
    "likes": 1
}


#### Test User Post

POST  http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

#### Test Get User
GET http://localhost:3001/api/users



#### Test User Login

POST  http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "salainen"
}